[package]
name = "dart_brigde_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "waku_dart_bridge"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dart-sys = "4.0.2"
ffi = "0.0.2"
once_cell = "1.18.0"
